### ISSUE TITLE
Throws attribute error at line 44 (used both python and python3 orbit.py to call)

### ISSUE THREAD

**Issue by biggysma11s** [s0md3v/Orbit#11]
__         
 |  |  _ |  ' _|_
 |__| |  |) |  |  v2.0

Traceback (most recent call last):
  File "/home/kali/Orbit/orbit.py", line 44, in <module>
    seeds = args.seeds.split(',')
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by biggysma11s** [comment]
Figured it out

**Comment by spyheros400** [comment]
Hey do you know how you fixed this i'm having the same issue
